export const RECEIVE_ADDRESS = 'RECEIVE_ADDRESS'
export const RECEIVE_CATEGORYS = 'RECEIVE_CATEGORYS'
export const RECEIVE_SHOPS = 'RECEIVE_SHOPS'
export const RECEIVE_USER = 'RECEIVE_USER'
export const LOGINOUT_USER = 'LOGINOUT_USER'

export const RECEIVE_GOODS = 'RECEIVE_GOODS'
export const RECEIVE_RATINGS = 'RECEIVE_RATINGS'
export const RECEIVE_INFO = 'RECEIVE_INFO'

export const COUNT_ADD = 'COUNT_ADD'
export const COUNT_REDUCE = 'COUNT_REDUCE'

